name: hs-di-example
version: '0.0.0'
category: Other
synopsis:    A small example of using hs-di to unit test effectful code.
description: A small example of using hs-di to unit test effectful code.
maintainer: Milan Nagy

extra-source-files:
- package.yaml
- README.md
- stack.yaml

ghc-options:
- -rtsopts
- -threaded
- -ddump-splices
- -ddump-to-file
- -with-rtsopts=-N
- -fdefer-type-errors

default-extensions:
- GADTs
- RankNTypes
- LambdaCase
- TemplateHaskell
- OverloadedStrings
- DefaultSignatures
- GeneralizedNewtypeDeriving
- NoMonomorphismRestriction

dependencies:
- text
- time
- base
- hs-di

library:
  source-dirs: library

executables:
  hs-di-example:
    dependencies:
    - hs-di-example
    main: Main.hs
    source-dirs: executable

tests:
  hs-di-example-test-suite:
    dependencies:
    - hspec
    - hs-di-example
    main: Main.hs
    source-dirs: test-suite
