name: hs-di-example
version: '0.0.0'
category: Other
synopsis:    A small example of using hs-di to unit test effectful code.
description: A small example of using hs-di to unit test effectful code.
maintainer: Milan Nagy

extra-source-files:
- README.md
- stack.yaml
- package.yaml

ghc-options:
- -ddump-splices
- -ddump-to-file
- -fdefer-type-errors

default-extensions:
- RankNTypes
- LambdaCase
- QuasiQuotes
- TemplateHaskell
- OverloadedStrings
- NoMonomorphismRestriction

dependencies:
- text
- time
- base
- hs-di
- interpolatedstring-perl6

library:
  source-dirs: library

executables:
  hs-di-example:
    dependencies:
    - hs-di-example
    main: Main.hs
    source-dirs: executable

tests:
  hs-di-example-test-suite:
    dependencies:
    - hspec
    - hs-di-example
    main: Main.hs
    source-dirs: test-suite
